# Generated by Django 4.1.5 on 2023-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todotask", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateTimeField(default="1993-07-12"),
            preserve_default=False,
        ),
    ]
